import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#f5b2de",
        "primary-fixed": "#ffdbd1",
        "primary": "#a7330e",
        "on-error-container": "#93000a",
        "outline-variant": "#e0bfb7",
        "primary-container": "#c94b26",
        "surface-container": "#f0eee9",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#68355a",
        "on-secondary-fixed": "#35092c",
        "on-primary-fixed-variant": "#872100",
        "outline": "#8c716a",
        "on-secondary-container": "#7b466c",
        "surface-bright": "#fbf9f4",
        "inverse-primary": "#ffb5a0",
        "surface-container-high": "#eae8e3",
        "on-tertiary-fixed": "#201145",
        "on-primary": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "primary-fixed-dim": "#ffb5a0",
        "secondary-fixed": "#ffd7ee",
        "surface-variant": "#e4e2dd",
        "on-surface": "#1b1c19",
        "on-background": "#1b1c19",
        "secondary": "#834c72",
        "inverse-surface": "#30312e",
        "surface-tint": "#ab3511",
        "surface": "#fbf9f4",
        "on-error": "#ffffff",
        "surface-dim": "#dbdad5",
        "error-container": "#ffdad6",
        "tertiary-container": "#7b6ca5",
        "on-tertiary-container": "#fffbff",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#4c3e73",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#3b0900",
        "on-surface-variant": "#59413b",
        "background": "#fbf9f4",
        "tertiary-fixed-dim": "#cfbdfc",
        "surface-container-highest": "#e4e2dd",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fffbff",
        "secondary-container": "#febae6",
        "inverse-on-surface": "#f2f1ec",
        "tertiary-fixed": "#e9ddff",
        "tertiary": "#62538a"
      },
      fontFamily: {
        "headline": ["Noto Serif"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" }
    },
  },
  plugins: [],
} satisfies Config;
